version: '3'

services:
  client:
    container_name: client
    build: ./client
    volumes:
      - ./client:/app
      - node_modules_client:/app/node_modules
    ports:
      - '8000:8000'
    depends_on:
      - server

  server:
    container_name: server
    build: ./server
    volumes:
      - ./server:/app
      - movies_server:/app/movies
      - node_modules_server:/app/node_modules
    ports:
      - '3000:3000'
      - '4000:4000'
    depends_on:
      - database
      - cache

  database:
    container_name: database
    image: mongo
    volumes:
      - data:/data/db
    ports:
      - '27017:27017'
  cache:
    image: redis
    ports:
      - 6379:6379

volumes:
  data:
  movies_server:
  node_modules_client:
  node_modules_server:
