version: "3"

services:
  server:
    container_name: server
    build: ./server
    volumes:
      - ./server:/app
    ports:
      - "8080:80"
      - "3000:3000"
      - "4000:4000"
    depends_on:
      - database
  client:
    container_name: client
    build: ./client
    volumes:
      - ./client:/app
    ports:
      - "8000:8000"
  database:
    container_name: database
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
